<?php
header('Content-Type: text/html; charset=utf-8');
require_once('security.php');

// Language handling
$_SESSION['lang'] = 'en';
$lang = $_SESSION['lang'];

// Language strings
$translations = [
    'en' => [
        'title' => 'Student List',
        'list_title' => 'Registered Students',
        'no_records' => 'No students found.',
        'sr_no' => '#',
        'father_name_label' => 'Father Name:',
        'mobile_label' => 'Mobile:',
        'reg_no_label' => 'Registration Number:',
        'guardian_mobile_label' => 'Guardian Mobile:',
        'guardian_cnic_label' => 'Guardian CNIC:',
        'class_or_course' => 'Class/Course:',
        'session_label' => 'Session:',
        'filter_by_class' => 'Filter by Class',
        'filter_by_village' => 'Filter by Village Council',
        'filter_by_status' => 'Filter by Status',
        'all_classes' => 'All Classes',
        'all_villages' => 'All Village Councils',
        'all_status' => 'All Students',
        'status_active' => 'Active',
        'status_leave' => 'Leave',
        'status_struck_off' => 'Struck Off',
        'status' => 'Status',
        'print_date' => 'Print Date',
        'total_students' => 'Total Students',
        'generated_by' => 'Generated by',
        'print_title' => 'Student List Report',
        'village_council' => 'Village Council'
    ]
];

require_once('conn_inc.php');

// Get filter parameters
$search = isset($_GET['search']) ? mysqli_real_escape_string($conn, $_GET['search']) : '';
$class_filter = isset($_GET['class_filter']) ? intval($_GET['class_filter']) : 0;
$village_filter = isset($_GET['village_filter']) ? intval($_GET['village_filter']) : 0;
$status_filter = isset($_GET['status_filter']) ? $_GET['status_filter'] : '0';

// Build WHERE clause
$where_conditions = [];

if (!empty($search)) {
    $where_conditions[] = "(
        sr.name LIKE '%$search%' OR 
        sr.father_name LIKE '%$search%' OR 
        sr.mobile LIKE '%$search%' OR 
        sr.reg_no LIKE '%$search%' OR 
        sr.guardian_name LIKE '%$search%' OR 
        sr.guardian_mobile LIKE '%$search%' OR 
        sr.guardian_cnic LIKE '%$search%' OR
        sr.id LIKE '%$search%'
    )";
}

if ($class_filter > 0) {
    $where_conditions[] = "sc.class_id = '$class_filter'";
}

if ($village_filter > 0) {
    $where_conditions[] = "sr.village_council_id = '$village_filter'";
}

if ($status_filter !== 'all') {
    $where_conditions[] = "sr.status = '$status_filter'";
}

$where_clause = '';
if (!empty($where_conditions)) {
    $where_clause = 'WHERE ' . implode(' AND ', $where_conditions);
}

// Get filter labels for display
$class_name = '';
if ($class_filter > 0) {
    $class_result = $conn->query("SELECT title FROM classes WHERE id = $class_filter");
    if ($class_result && $class_result->num_rows > 0) {
        $class_row = $class_result->fetch_assoc();
        $class_name = $class_row['title'];
    }
}

$village_name = '';
if ($village_filter > 0) {
    $village_result = $conn->query("SELECT title FROM village_councils WHERE id = $village_filter");
    if ($village_result && $village_result->num_rows > 0) {
        $village_row = $village_result->fetch_assoc();
        $village_name = $village_row['title'];
    }
}

$status_text = '';
if ($status_filter == '0') $status_text = $translations[$lang]['status_active'];
elseif ($status_filter == '1') $status_text = $translations[$lang]['status_leave'];
elseif ($status_filter == '2') $status_text = $translations[$lang]['status_struck_off'];
elseif ($status_filter == 'all') $status_text = $translations[$lang]['all_status'];

// Get data for printing
$query = "SELECT 
    sr.id,
    sr.name,
    sr.father_name,
    sr.mobile,
    sr.reg_no,
    sr.guardian_name,
    sr.guardian_mobile,
    sr.guardian_cnic,
    sr.status,
    c.title AS class_title,
    s.title AS section_title,
    ses.title AS session_title,
    vc.title AS village_council_title
FROM student_registration sr
LEFT JOIN (
    SELECT sc1.student_registration_id, sc1.class_id, sc1.session_id
    FROM student_class sc1
    INNER JOIN (
        SELECT student_registration_id, MAX(id) AS max_id
        FROM student_class
        GROUP BY student_registration_id
    ) sc2 ON sc1.id = sc2.max_id
) sc ON sr.id = sc.student_registration_id
LEFT JOIN classes c ON sc.class_id = c.id
LEFT JOIN class_sections cs ON sc.class_id = cs.class_id
LEFT JOIN sections s ON cs.section_id = s.id
LEFT JOIN sessions ses ON sc.session_id = ses.id
LEFT JOIN village_councils vc ON sr.village_council_id = vc.id
$where_clause
ORDER BY sr.id DESC";

$result = $conn->query($query);
$total_students = $result ? $result->num_rows : 0;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $translations[$lang]['print_title']; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Inter', sans-serif;
            padding: 30px;
            background: white;
        }
        .print-header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #667eea;
        }
        .print-title {
            font-size: 24px;
            font-weight: 700;
            color: #333;
            margin-bottom: 10px;
        }
        .print-subtitle {
            font-size: 14px;
            color: #666;
            margin-bottom: 5px;
        }
        .filter-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            font-size: 13px;
        }
        .filter-badge {
            background: #667eea;
            color: white;
            padding: 3px 8px;
            border-radius: 12px;
            margin-right: 5px;
            display: inline-block;
            margin-bottom: 5px;
        }
        .table {
            font-size: 12px;
        }
        .table th {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            font-weight: 600;
            padding: 10px;
            white-space: nowrap;
        }
        .table td {
            padding: 8px;
            vertical-align: middle;
        }
        .status-badge {
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 11px;
            font-weight: 600;
            display: inline-block;
        }
        .status-active {
            background: #d4edda;
            color: #155724;
        }
        .status-leave {
            background: #fff3cd;
            color: #856404;
        }
        .status-struck {
            background: #f8d7da;
            color: #721c24;
        }
        .print-footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            font-size: 12px;
            color: #666;
        }
        @media print {
            .no-print {
                display: none !important;
            }
            body {
                padding: 0;
            }
            .table th {
                background: #667eea !important;
                color: white !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
            .status-active, .status-leave, .status-struck {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
        }
        .print-button {
            position: fixed;
            bottom: 30px;
            right: 30px;
            z-index: 1000;
        }
    </style>
</head>
<body>
    <div class="print-button no-print">
        <button onclick="window.print();" class="btn btn-lg btn-success">
            <i class="fas fa-print"></i> Print / Save PDF
        </button>
        <button onclick="window.close();" class="btn btn-lg btn-secondary">
            <i class="fas fa-times"></i> Close
        </button>
    </div>

    <div class="print-header">
        <h1 class="print-title">Dar-e-Arqam School System</h1>
        <h2 class="print-subtitle"><?php echo $translations[$lang]['print_title']; ?></h2>
        <div class="print-subtitle">
            <?php echo $translations[$lang]['print_date']; ?>: <?php echo date('d F Y, h:i A'); ?>
        </div>
        <div class="print-subtitle">
            <?php echo $translations[$lang]['generated_by']; ?>: <?php echo htmlspecialchars($_SESSION['username'] ?? 'Admin'); ?>
        </div>
    </div>

    <div class="filter-info">
        <strong>Filter Criteria:</strong><br>
        <?php if (!empty($search)): ?>
            <span class="filter-badge">Search: <?php echo htmlspecialchars($search); ?></span>
        <?php endif; ?>
        
        <?php if ($class_filter > 0): ?>
            <span class="filter-badge">Class: <?php echo htmlspecialchars($class_name); ?></span>
        <?php else: ?>
            <span class="filter-badge"><?php echo $translations[$lang]['all_classes']; ?></span>
        <?php endif; ?>
        
        <?php if ($village_filter > 0): ?>
            <span class="filter-badge">Village: <?php echo htmlspecialchars($village_name); ?></span>
        <?php else: ?>
            <span class="filter-badge"><?php echo $translations[$lang]['all_villages']; ?></span>
        <?php endif; ?>
        
        <span class="filter-badge">Status: <?php echo $status_text; ?></span>
        
        <span class="filter-badge"><?php echo $translations[$lang]['total_students']; ?>: <?php echo $total_students; ?></span>
    </div>

    <?php if ($result && $result->num_rows > 0): ?>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Student Information</th>
                    <th>Guardian Information</th>
                    <th>Class/Session</th>
                    <th><?php echo $translations[$lang]['village_council']; ?></th>
                    <th><?php echo $translations[$lang]['status']; ?></th>
                    <th>Reg No.</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                $count = 1;
                while ($row = $result->fetch_assoc()): 
                    $status_class = '';
                    $status_text_display = '';
                    if ($row['status'] == 0) {
                        $status_class = 'status-active';
                        $status_text_display = $translations[$lang]['status_active'];
                    } elseif ($row['status'] == 1) {
                        $status_class = 'status-leave';
                        $status_text_display = $translations[$lang]['status_leave'];
                    } elseif ($row['status'] == 2) {
                        $status_class = 'status-struck';
                        $status_text_display = $translations[$lang]['status_struck_off'];
                    }
                ?>
                <tr>
                    <td><?php echo $count++; ?></td>
                    <td>
                        <strong><?php echo htmlspecialchars($row['name']); ?></strong><br>
                        <small><?php echo $translations[$lang]['father_name_label']; ?> <?php echo htmlspecialchars($row['father_name']); ?></small><br>
                        <small><?php echo $translations[$lang]['mobile_label']; ?> <?php echo htmlspecialchars($row['mobile']); ?></small>
                    </td>
                    <td>
                        <strong><?php echo htmlspecialchars($row['guardian_name']); ?></strong><br>
                        <small><?php echo $translations[$lang]['guardian_mobile_label']; ?> <?php echo htmlspecialchars($row['guardian_mobile']); ?></small><br>
                        <small><?php echo $translations[$lang]['guardian_cnic_label']; ?> <?php echo htmlspecialchars($row['guardian_cnic']); ?></small>
                    </td>
                    <td>
                        <?php echo htmlspecialchars($row['class_title'] ?? 'Not Assigned'); ?>
                        <?php if (!empty($row['section_title'])): ?>
                            (<?php echo htmlspecialchars($row['section_title']); ?>)
                        <?php endif; ?><br>
                        <small><?php echo $translations[$lang]['session_label']; ?> <?php echo htmlspecialchars($row['session_title'] ?? 'Not Assigned'); ?></small>
                    </td>
                    <td><?php echo htmlspecialchars($row['village_council_title'] ?? 'N/A'); ?></td>
                    <td>
                        <span class="status-badge <?php echo $status_class; ?>">
                            <?php echo $status_text_display; ?>
                        </span>
                    </td>
                    <td><?php echo htmlspecialchars($row['reg_no']); ?></td>
                </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
    </div>
    
    <div class="print-footer">
        <div class="row">
            <div class="col-md-6">
                <strong><?php echo $translations[$lang]['total_students']; ?>:</strong> <?php echo $total_students; ?>
            </div>
            <div class="col-md-6 text-right">
                <strong>Report ID:</strong> RPT-<?php echo date('YmdHis'); ?>
            </div>
        </div>
    </div>
    <?php else: ?>
    <div class="alert alert-info text-center">
        <h4><?php echo $translations[$lang]['no_records']; ?></h4>
    </div>
    <?php endif; ?>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    
    <script>
        $(document).ready(function() {
            // Auto trigger print dialog? Uncomment below if you want
            // setTimeout(function() {
            //     window.print();
            // }, 500);
        });
    </script>
</body>
</html>
<?php $conn->close(); ?>