<?php 
header('Content-Type: text/html; charset=utf-8');
require_once('security.php');

// Language handling
$_SESSION['lang'] = 'en'; // Default to English
$lang = $_SESSION['lang'];

// Language strings
$translations = [
    'en' => [
        'title' => 'Student List',
        'list_title' => 'Registered Students',
        'no_records' => 'No students found.',
        'sr_no' => '#',
        'student_id' => 'Student ID',
        'actions' => 'Actions',
        'edit' => 'Edit',
        'print_registration_form' => 'Print Registration Form',
        'print_list' => 'Print List',
        'print_filtered_list' => 'Print Current List',
        'father_name_label' => 'Father Name:',
        'mobile_label' => 'Mobile:',
        'reg_no_label' => 'Registration Number:',
        'guardian_mobile_label' => 'Guardian Mobile:',
        'guardian_cnic_label' => 'Guardian CNIC:',
        'class_or_course' => 'Class/Course:',
        'session_label' => 'Session:',
        'search_placeholder' => 'Search by name, father name, mobile, ID...',
        'search_button' => 'Search',
        'reset_button' => 'Reset',
        'add_new_student' => 'Add New Student',
        'delete_confirm' => 'Are you sure you want to delete this student record?',
        'delete_success' => 'Student deleted successfully!',
        'error' => 'Error: ',
        'filter_by_class' => 'Filter by Class',
        'filter_by_village' => 'Filter by Village Council',
        'filter_by_status' => 'Filter by Status',
        'select_class' => '-- Select Class --',
        'select_village' => '-- Select Village Council --',
        'select_status' => '-- Select Status --',
        'all_classes' => 'All Classes',
        'all_villages' => 'All Village Councils',
        'all_status' => 'All Students',
        'status_active' => 'Active',
        'status_leave' => 'Leave',
        'status_struck_off' => 'Struck Off',
        'status_label' => 'Status:',
        'active_students' => 'Active Students',
        'status' => 'Status',
        'print_date' => 'Print Date',
        'total_students' => 'Total Students',
        'generated_by' => 'Generated by',
        'print_title' => 'Student List Report',
        'village_council' => 'Village Council',
        // New status update translations
        'update_status' => 'Update Status',
        'select_new_status' => 'Select New Status',
        'status_updated' => 'Student status updated successfully!',
        'status_update_confirm' => 'Are you sure you want to change this student\'s status?',
        'status_update_error' => 'Error updating status: ',
        'change_status' => 'Change Status',
        'current_status' => 'Current Status'
    ]
];

// Create database connection
require_once('conn_inc.php');

// Handle status update
if (isset($_POST['update_status'])) {
    $student_id = intval($_POST['student_id']);
    $new_status = intval($_POST['new_status']);
    
    $stmt = $conn->prepare("UPDATE student_registration SET status = ? WHERE id = ?");
    $stmt->bind_param("ii", $new_status, $student_id);
    
    if ($stmt->execute()) {
        $_SESSION['message'] = $translations[$lang]['status_updated'];
        $_SESSION['message_type'] = 'success';
    } else {
        $_SESSION['message'] = $translations[$lang]['status_update_error'] . $stmt->error;
        $_SESSION['message_type'] = 'danger';
    }
    
    $stmt->close();
    
    // Redirect back with current filters
    $redirect_url = "student_list.php";
    $params = [];
    if (!empty($_GET['search'])) $params['search'] = $_GET['search'];
    if (!empty($_GET['class_filter'])) $params['class_filter'] = $_GET['class_filter'];
    if (!empty($_GET['village_filter'])) $params['village_filter'] = $_GET['village_filter'];
    if (!empty($_GET['status_filter'])) $params['status_filter'] = $_GET['status_filter'];
    
    if (!empty($params)) {
        $redirect_url .= "?" . http_build_query($params);
    }
    
    header("Location: " . $redirect_url);
    exit();
}

// Handle student deletion
if (isset($_GET['delete'])) {
    $id = intval($_GET['delete']);
    $stmt = $conn->prepare("DELETE FROM student_registration WHERE id = ?");
    $stmt->bind_param("i", $id);
    
    if ($stmt->execute()) {
        $_SESSION['message'] = $translations[$lang]['delete_success'];
        $_SESSION['message_type'] = 'success';
    } else {
        $_SESSION['message'] = $translations[$lang]['error'] . $stmt->error;
        $_SESSION['message_type'] = 'danger';
    }
    
    $stmt->close();
    
    // Redirect back with current filters
    $redirect_url = "student_list.php";
    $params = [];
    if (!empty($_GET['search'])) $params['search'] = $_GET['search'];
    if (!empty($_GET['class_filter'])) $params['class_filter'] = $_GET['class_filter'];
    if (!empty($_GET['village_filter'])) $params['village_filter'] = $_GET['village_filter'];
    if (!empty($_GET['status_filter'])) $params['status_filter'] = $_GET['status_filter'];
    
    if (!empty($params)) {
        $redirect_url .= "?" . http_build_query($params);
    }
    
    header("Location: " . $redirect_url);
    exit();
}

// Fetch filter options
$classes = [];
$village_councils = [];

// Fetch classes for filter
$class_filter_query = $conn->query("
    SELECT 
        c.id AS class_id,
        c.title AS class_title,
        s.id AS section_id,
        s.title AS section_title
    FROM classes c
    LEFT JOIN class_sections cs ON cs.class_id = c.id
    LEFT JOIN sections s ON s.id = cs.section_id
    ORDER BY c.title, s.title
");

while ($row = $class_filter_query->fetch_assoc()) {
    $classes[$row['class_id']] = $row['class_title'] . ($row['section_title'] ? ' - ' . $row['section_title'] : '');
}

// Fetch village councils for filter
$village_filter_query = $conn->query("SELECT id, title FROM village_councils ORDER BY title");
while ($row = $village_filter_query->fetch_assoc()) {
    $village_councils[$row['id']] = $row['title'];
}

// Handle filters
$search = isset($_GET['search']) ? mysqli_real_escape_string($conn, $_GET['search']) : '';
$class_filter = isset($_GET['class_filter']) ? intval($_GET['class_filter']) : 0;
$village_filter = isset($_GET['village_filter']) ? intval($_GET['village_filter']) : 0;
$status_filter = isset($_GET['status_filter']) ? $_GET['status_filter'] : '0'; // Default to Active (status 0)

// Build WHERE clause
$where_conditions = [];

if (!empty($search)) {
    $where_conditions[] = "(
        sr.name LIKE '%$search%' OR 
        sr.father_name LIKE '%$search%' OR 
        sr.mobile LIKE '%$search%' OR 
        sr.reg_no LIKE '%$search%' OR 
        sr.guardian_name LIKE '%$search%' OR 
        sr.guardian_mobile LIKE '%$search%' OR 
        sr.guardian_cnic LIKE '%$search%' OR
        sr.id LIKE '%$search%'
    )";
}

if ($class_filter > 0) {
    $where_conditions[] = "sc.class_id = '$class_filter'";
}

if ($village_filter > 0) {
    $where_conditions[] = "sr.village_council_id = '$village_filter'";
}

// Status filter - if 'all' selected, show all statuses
if ($status_filter !== 'all') {
    $where_conditions[] = "sr.status = '$status_filter'";
}

$where_clause = '';
if (!empty($where_conditions)) {
    $where_clause = 'WHERE ' . implode(' AND ', $where_conditions);
}

// Get data for listing - INCLUDING sr.status field
$query = "SELECT 
    sr.id,
    sr.name,
    sr.father_name,
    sr.mobile,
    sr.reg_no,
    sr.guardian_name,
    sr.guardian_mobile,
    sr.guardian_cnic,
    sr.village_council_id,
    sr.status,
    c.title AS class_title,
    s.title AS section_title,
    ses.title AS session_title,
    vc.title AS village_council_title
FROM student_registration sr
LEFT JOIN (
    SELECT sc1.student_registration_id, sc1.class_id, sc1.session_id
    FROM student_class sc1
    INNER JOIN (
        SELECT student_registration_id, MAX(id) AS max_id
        FROM student_class
        GROUP BY student_registration_id
    ) sc2 ON sc1.id = sc2.max_id
) sc ON sr.id = sc.student_registration_id
LEFT JOIN classes c ON sc.class_id = c.id
LEFT JOIN class_sections cs ON sc.class_id = cs.class_id
LEFT JOIN sections s ON cs.section_id = s.id
LEFT JOIN sessions ses ON sc.session_id = ses.id
LEFT JOIN village_councils vc ON sr.village_council_id = vc.id
$where_clause
ORDER BY sr.id DESC";

$result = $conn->query($query);
$total_students = $result ? $result->num_rows : 0;

// Build query string for print
$print_query_string = http_build_query([
    'search' => $search,
    'class_filter' => $class_filter,
    'village_filter' => $village_filter,
    'status_filter' => $status_filter
]);

// Prepare JavaScript translations
$js_translations = [
    'delete_confirm' => $translations[$lang]['delete_confirm'],
    'status_update_confirm' => $translations[$lang]['status_update_confirm'],
    'status_active' => $translations[$lang]['status_active'],
    'status_leave' => $translations[$lang]['status_leave'],
    'status_struck_off' => $translations[$lang]['status_struck_off']
];
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <title><?php echo $translations[$lang]['title']; ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <script>
    // Define global translations for JavaScript
    var lang = <?php echo json_encode($js_translations, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP); ?>;
    </script>
    <style>
        .panel {
            background: white;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            margin-bottom: 30px;
            overflow: hidden;
        }
        .panel-heading {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 15px 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .panel-title {
            margin: 0;
            font-weight: 600;
        }
        .panel-body {
            padding: 20px;
        }
        .search-box {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .filter-row {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 15px;
        }
        .btn-info {
            background: linear-gradient(135deg, #17a2b8 0%, #138496 100%);
            border: none;
        }
        .btn-info:hover {
            background: linear-gradient(135deg, #138496 0%, #117a8b 100%);
        }
        .btn-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border: none;
        }
        .btn-primary:hover {
            background: linear-gradient(135deg, #5a6fd8 0%, #6a4190 100%);
        }
        .btn-warning {
            background: linear-gradient(135deg, #ffc107 0%, #e0a800 100%);
            border: none;
        }
        .btn-warning:hover {
            background: linear-gradient(135deg, #e0a800 0%, #c69500 100%);
        }
        .btn-print {
            background: linear-gradient(135deg, #28a745 0%, #218838 100%);
            border: none;
            color: white;
        }
        .btn-print:hover {
            background: linear-gradient(135deg, #218838 0%, #1e7e34 100%);
            color: white;
        }
        .btn-success {
            background: linear-gradient(135deg, #28a745 0%, #218838 100%);
            border: none;
        }
        .btn-success:hover {
            background: linear-gradient(135deg, #218838 0%, #1e7e34 100%);
        }
        .btn-secondary {
            background: linear-gradient(135deg, #6c757d 0%, #5a6268 100%);
            border: none;
            color: white;
        }
        .btn-secondary:hover {
            background: linear-gradient(135deg, #5a6268 0%, #4e555b 100%);
        }
        .table th {
            background-color: #f8f9fa;
            border-top: none;
            font-weight: 600;
        }
        .alert {
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .action-buttons .btn {
            margin: 2px;
        }
        .results-info {
            background: #e9ecef;
            padding: 10px 15px;
            border-radius: 5px;
            margin-bottom: 15px;
            font-weight: 500;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .filter-label {
            font-weight: 600;
            margin-bottom: 5px;
            color: #495057;
        }
        .badge-filter {
            background: #6c757d;
            color: white;
            padding: 5px 10px;
            border-radius: 15px;
            font-size: 12px;
            margin-left: 5px;
        }
        .form-control {
            border-radius: 5px;
            border: 1px solid #ced4da;
        }
        .input-group-text {
            background-color: #f8f9fa;
            border: 1px solid #ced4da;
        }
        /* Status Badge Styles */
        .status-badge {
            padding: 5px 10px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
            display: inline-block;
            text-align: center;
            min-width: 80px;
        }
        .status-active {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }
        .status-leave {
            background: #fff3cd;
            color: #856404;
            border: 1px solid #ffeeba;
        }
        .status-struck {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }
        /* Print button styles */
        .print-btn-container {
            display: inline-block;
            margin-left: 15px;
        }
        .header-actions {
            display: flex;
            align-items: center;
        }
        /* Make the table responsive for extra column */
        .table-responsive {
            overflow-x: auto;
        }
        /* Adjust column widths */
        .table th, .table td {
            vertical-align: middle;
        }
        /* Status update modal styles */
        .modal-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-bottom: none;
        }
        .modal-header .close {
            color: white;
            opacity: 0.8;
        }
        .modal-header .close:hover {
            opacity: 1;
        }
        .modal-title {
            font-weight: 600;
        }
        .modal-body {
            padding: 20px;
        }
        .modal-footer {
            border-top: 1px solid #dee2e6;
            padding: 15px;
        }
        .status-option {
            padding: 12px;
            margin-bottom: 10px;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            cursor: pointer;
            transition: all 0.2s;
        }
        .status-option:hover {
            background-color: #f8f9fa;
            border-color: #667eea;
        }
        .status-option input[type="radio"] {
            margin-right: 10px;
        }
        .status-option label {
            font-weight: 500;
            margin-bottom: 0;
            cursor: pointer;
            width: 100%;
        }
        .status-description {
            font-size: 12px;
            color: #6c757d;
            margin-left: 25px;
        }
        .current-status-info {
            background: #e9ecef;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 15px;
        }
        
    </style>
</head>

<body>
    <?php require_once('navbar.php'); ?>

    <!-- Dashboard -->
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!-- Add New Student Button -->
                <div class="mb-3 text-right">
                    <a href="student_registration.php" class="btn btn-primary">
                        <i class="fas fa-plus"></i> <?php echo $translations[$lang]['add_new_student']; ?>
                    </a>
                </div>

                <!-- Panel for Student List -->
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $translations[$lang]['list_title']; ?></h3>
                        <div class="header-actions">
                            <a href="print_student_list.php?<?php echo $print_query_string; ?>" 
                               class="btn btn-print btn-sm" 
                               target="_blank"
                               title="<?php echo $translations[$lang]['print_filtered_list']; ?>">
                                <i class="fas fa-print"></i> <?php echo $translations[$lang]['print_list']; ?>
                                <?php if ($total_students > 0): ?>
                                <span class="badge badge-light ml-1"><?php echo $total_students; ?></span>
                                <?php endif; ?>
                            </a>
                        </div>
                    </div>
                    <div class="panel-body">
                        <!-- Search and Filter Box -->
                        <div class="search-box">
                            <form method="GET" action="" id="filterForm">
                                <!-- Search Input -->
                                <div class="form-group">
                                    <label class="filter-label">
                                        <i class="fas fa-search"></i> <?php echo $translations[$lang]['search_placeholder']; ?>
                                    </label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" 
                                               name="search" 
                                               placeholder="<?php echo $translations[$lang]['search_placeholder']; ?>"
                                               value="<?php echo htmlspecialchars($search); ?>">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-info">
                                                <i class="fas fa-search"></i> <?php echo $translations[$lang]['search_button']; ?>
                                            </button>
                                        </div>
                                    </div>
                                </div>

                                <!-- Filter Row -->
                                <div class="row filter-row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="filter-label">
                                                <i class="fas fa-graduation-cap"></i> <?php echo $translations[$lang]['filter_by_class']; ?>
                                            </label>
                                            <select class="form-control" name="class_filter" id="class_filter">
                                                <option value="0"><?php echo $translations[$lang]['all_classes']; ?></option>
                                                <?php foreach ($classes as $id => $name): ?>
                                                <option value="<?php echo $id; ?>" 
                                                    <?php echo ($class_filter == $id) ? 'selected' : ''; ?>>
                                                    <?php echo htmlspecialchars($name); ?>
                                                </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="filter-label">
                                                <i class="fas fa-map-marker-alt"></i> <?php echo $translations[$lang]['filter_by_village']; ?>
                                            </label>
                                            <select class="form-control" name="village_filter" id="village_filter">
                                                <option value="0"><?php echo $translations[$lang]['all_villages']; ?></option>
                                                <?php foreach ($village_councils as $id => $name): ?>
                                                <option value="<?php echo $id; ?>" 
                                                    <?php echo ($village_filter == $id) ? 'selected' : ''; ?>>
                                                    <?php echo htmlspecialchars($name); ?>
                                                </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="filter-label">
                                                <i class="fas fa-flag"></i> <?php echo $translations[$lang]['filter_by_status']; ?>
                                            </label>
                                            <select class="form-control" name="status_filter" id="status_filter">
                                                <option value="0" <?php echo ($status_filter == '0') ? 'selected' : ''; ?>>
                                                    <?php echo $translations[$lang]['active_students']; ?>
                                                </option>
                                                <option value="1" <?php echo ($status_filter == '1') ? 'selected' : ''; ?>>
                                                    <?php echo $translations[$lang]['status_leave']; ?>
                                                </option>
                                                <option value="2" <?php echo ($status_filter == '2') ? 'selected' : ''; ?>>
                                                    <?php echo $translations[$lang]['status_struck_off']; ?>
                                                </option>
                                                <option value="all" <?php echo ($status_filter == 'all') ? 'selected' : ''; ?>>
                                                    <?php echo $translations[$lang]['all_status']; ?>
                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-3 d-flex align-items-end">
                                        <div class="form-group w-100">
                                            <div class="btn-group w-100" role="group">
                                                <button type="submit" class="btn btn-info w-50">
                                                    <i class="fas fa-filter"></i> <?php echo $translations[$lang]['search_button']; ?>
                                                </button>
                                                <?php if ($search || $class_filter > 0 || $village_filter > 0 || $status_filter != '0'): ?>
                                                <a href="student_list.php" class="btn btn-warning w-50">
                                                    <i class="fas fa-times"></i> <?php echo $translations[$lang]['reset_button']; ?>
                                                </a>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <!-- Results Information -->
                        <?php if ($search || $class_filter > 0 || $village_filter > 0 || $status_filter != '0'): ?>
                        <div class="results-info">
                            <div>
                                <i class="fas fa-info-circle"></i> Showing 
                                <strong><?php echo $total_students; ?></strong> student(s)
                                <?php if ($search): ?>
                                    <span class="badge-filter">Search: "<?php echo htmlspecialchars($search); ?>"</span>
                                <?php endif; ?>
                                <?php if ($class_filter > 0 && isset($classes[$class_filter])): ?>
                                    <span class="badge-filter">Class: <?php echo htmlspecialchars($classes[$class_filter]); ?></span>
                                <?php endif; ?>
                                <?php if ($village_filter > 0 && isset($village_councils[$village_filter])): ?>
                                    <span class="badge-filter">Village: <?php echo htmlspecialchars($village_councils[$village_filter]); ?></span>
                                <?php endif; ?>
                                <?php if ($status_filter != '0'): ?>
                                    <?php 
                                        $status_text = '';
                                        if ($status_filter == '1') $status_text = $translations[$lang]['status_leave'];
                                        elseif ($status_filter == '2') $status_text = $translations[$lang]['status_struck_off'];
                                        elseif ($status_filter == 'all') $status_text = $translations[$lang]['all_status'];
                                    ?>
                                    <span class="badge-filter">Status: <?php echo $status_text; ?></span>
                                <?php endif; ?>
                            </div>
                            <div>
                                <a href="print_student_list.php?<?php echo $print_query_string; ?>" 
                                   class="btn btn-sm btn-success" 
                                   target="_blank"
                                   title="<?php echo $translations[$lang]['print_filtered_list']; ?>">
                                    <i class="fas fa-print"></i> Print This List
                                </a>
                            </div>
                        </div>
                        <?php endif; ?>

                        <?php if (isset($_SESSION['message'])): ?>
                        <div class="alert alert-<?php echo $_SESSION['message_type']; ?> alert-dismissible fade show">
                            <?php 
                            echo $_SESSION['message']; 
                            unset($_SESSION['message'], $_SESSION['message_type']);
                            ?>
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                        </div>
                        <?php endif; ?>

                        <?php if ($result && $result->num_rows > 0): ?>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th width="5%"><?php echo $translations[$lang]['sr_no']; ?></th>
                                      
                                        <th width="18%">Student Info</th>
                                        <th width="18%">Guardian Info</th>
                                        <th width="15%">Class/Session Info</th>
                                        <th width="10%">VC</th>
                                        <th width="10%"><?php echo $translations[$lang]['status']; ?></th>
                                        <th width="19%" class="text-center"><?php echo $translations[$lang]['actions']; ?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php 
                                        $count = 1;
                                        while ($row = $result->fetch_assoc()): 
                                        // Determine status class and text
                                        $status_class = '';
                                        $status_text = '';
                                        if ($row['status'] == 0) {
                                            $status_class = 'status-active';
                                            $status_text = $translations[$lang]['status_active'];
                                        } elseif ($row['status'] == 1) {
                                            $status_class = 'status-leave';
                                            $status_text = $translations[$lang]['status_leave'];
                                        } elseif ($row['status'] == 2) {
                                            $status_class = 'status-struck';
                                            $status_text = $translations[$lang]['status_struck_off'];
                                        } else {
                                            $status_class = 'status-active';
                                            $status_text = $translations[$lang]['status_active'];
                                        }
                                    ?>
                                    <tr>
                                        <td><?php echo $count++; ?></td>
                                     
                                        <td>
                                            <?php echo '<span style="font-size: 23px !important; font-weight:bold;">'.$row['id'].'</span>'; ?>
                                            <strong><?php echo htmlspecialchars($row['name']); ?></strong><br>
                                            <small class="text-muted">
                                                <?php echo $translations[$lang]['father_name_label']; ?>:
                                                <?php echo htmlspecialchars($row['father_name']); ?><br>
                                                <?php echo $translations[$lang]['mobile_label']; ?>:
                                                <?php echo htmlspecialchars($row['mobile']); ?><br>
                                                <?php echo $translations[$lang]['reg_no_label']; ?>:
                                                <?php echo htmlspecialchars($row['reg_no']); ?>
                                            </small>
                                        </td>
                                        <td>
                                            <strong><?php echo htmlspecialchars($row['guardian_name']); ?></strong><br>
                                            <small class="text-muted">
                                                <?php echo $translations[$lang]['guardian_mobile_label']; ?>:
                                                <?php echo htmlspecialchars($row['guardian_mobile']); ?><br>
                                                <?php echo $translations[$lang]['guardian_cnic_label']; ?>:
                                                <?php echo htmlspecialchars($row['guardian_cnic']); ?>
                                            </small>
                                        </td>
                                        <td>
                                            <strong><?php echo $translations[$lang]['class_or_course']; ?></strong><br>
                                            <?php 
                                                echo htmlspecialchars($row['class_title'] ?? 'Not Assigned');
                                                if (!empty($row['section_title'])) {
                                                    echo " (" . htmlspecialchars($row['section_title']) . ")";
                                                }
                                            ?>
                                            <br>
                                            <small class="text-muted">
                                                <?php echo $translations[$lang]['session_label']; ?>:
                                                <?php echo htmlspecialchars($row['session_title'] ?? 'Not Assigned'); ?>
                                            </small>
                                        </td>
                                        <td>
                                            <?php echo htmlspecialchars($row['village_council_title'] ?? 'N/A'); ?>
                                        </td>
                                        <td class="text-center">
                                            <span class="status-badge <?php echo $status_class; ?>" id="status-badge-<?php echo $row['id']; ?>">
                                                <?php echo $status_text; ?>
                                            </span>
                                        </td>
                                        <td class="action-buttons text-center">
                                            <div class="btn-group" role="group">
                                                <a href="student_registration.php?edit=<?php echo $row['id']; ?>"
                                                    class="btn btn-primary btn-sm"
                                                    title="<?php echo $translations[$lang]['edit']; ?>"
                                                    data-toggle="tooltip">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a href="student_registration_print.php?id=<?php echo $row['id']; ?>"
                                                    class="btn btn-info btn-sm"
                                                    target="_blank"
                                                    title="<?php echo $translations[$lang]['print_registration_form']; ?>"
                                                    data-toggle="tooltip">
                                                    <i class="fas fa-print"></i>
                                                </a>
                                                <a href="student_fee_assignment.php?id=<?php echo $row['id']; ?>"
                                                    class="btn btn-success btn-sm"
                                                    title="Collect Fee"
                                                    data-toggle="tooltip">
                                                    <i class="fas fa-money-bill"></i>
                                                </a>
                                                <button type="button"
                                                    class="btn btn-secondary btn-sm status-update-btn"
                                                    data-student-id="<?php echo $row['id']; ?>"
                                                    data-student-name="<?php echo htmlspecialchars($row['name'], ENT_QUOTES, 'UTF-8'); ?>"
                                                    data-student-status="<?php echo $row['status']; ?>"
                                                    title="<?php echo $translations[$lang]['change_status']; ?>">
                                                    <i class="fas fa-exchange-alt"></i>
                                                </button>
                                                
                                            </div>
                                        </td>
                                    </tr>
                                    <?php endwhile; ?>
                                </tbody>
                            </table>
                        </div>
                        <?php else: ?>
                        <div class="alert alert-info text-center">
                            <i class="fas fa-info-circle fa-2x mb-3"></i><br>
                            <h4><?php echo $translations[$lang]['no_records']; ?></h4>
                            <?php if ($search || $class_filter > 0 || $village_filter > 0 || $status_filter != '0'): ?>
                            <p class="mt-3">
                                <a href="student_list.php" class="btn btn-info">
                                    <i class="fas fa-times"></i> <?php echo $translations[$lang]['reset_button']; ?> Filters
                                </a>
                            </p>
                            <?php endif; ?>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Status Update Modal -->
    <div class="modal fade" id="statusModal" tabindex="-1" role="dialog" aria-labelledby="statusModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="statusModalLabel">
                        <i class="fas fa-exchange-alt"></i> <?php echo $translations[$lang]['update_status']; ?>
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="POST" action="" id="statusForm">
                    <div class="modal-body">
                        <input type="hidden" name="update_status" value="1">
                        <input type="hidden" name="student_id" id="modal_student_id" value="">
                        
                        <!-- Current Status Display -->
                        <div class="current-status-info">
                            <strong><?php echo $translations[$lang]['current_status']; ?>:</strong> 
                            <span id="current_status_text"></span>
                        </div>
                        
                        <!-- Student Name -->
                        <div class="form-group">
                            <label><strong>Student:</strong></label>
                            <p class="form-control-static" id="modal_student_name"></p>
                        </div>
                        
                        <!-- Status Options -->
                        <div class="form-group">
                            <label><strong><?php echo $translations[$lang]['select_new_status']; ?>:</strong></label>
                            
                            <div class="status-option" onclick="selectStatus(0)">
                                <label>
                                    <input type="radio" name="new_status" value="0" id="status_active">
                                    <span class="status-badge status-active"><?php echo $translations[$lang]['status_active']; ?></span>
                                </label>
                                <div class="status-description">Student is currently enrolled and attending classes</div>
                            </div>
                            
                            <div class="status-option" onclick="selectStatus(1)">
                                <label>
                                    <input type="radio" name="new_status" value="1" id="status_leave">
                                    <span class="status-badge status-leave"><?php echo $translations[$lang]['status_leave']; ?></span>
                                </label>
                                <div class="status-description">Student is on temporary leave/break</div>
                            </div>
                            
                            <div class="status-option" onclick="selectStatus(2)">
                                <label>
                                    <input type="radio" name="new_status" value="2" id="status_struck">
                                    <span class="status-badge status-struck"><?php echo $translations[$lang]['status_struck_off']; ?></span>
                                </label>
                                <div class="status-description">Student has been permanently removed from rolls</div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                            <i class="fas fa-times"></i> Cancel
                        </button>
                        <button type="submit" class="btn btn-primary" id="updateStatusBtn">
                            <i class="fas fa-save"></i> Update Status
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
    $(document).ready(function() {
        // Auto-focus on search input
        $('input[name="search"]').focus();
        
        // Initialize tooltips
        $('[data-toggle="tooltip"]').tooltip();
        
        // Auto-submit filters on change
        $('#class_filter, #village_filter, #status_filter').change(function() {
            $('#filterForm').submit();
        });
        
        // Status update button click handler
        $(document).on('click', '.status-update-btn', function(e) {
            e.preventDefault();
            var studentId = $(this).data('student-id');
            var studentName = $(this).data('student-name');
            var studentStatus = $(this).data('student-status');
            
            // Set values in modal
            $('#modal_student_id').val(studentId);
            $('#modal_student_name').text(studentName);
            
            // Set current status text
            var statusText = '';
            switch(parseInt(studentStatus)) {
                case 0:
                    statusText = lang.status_active;
                    break;
                case 1:
                    statusText = lang.status_leave;
                    break;
                case 2:
                    statusText = lang.status_struck_off;
                    break;
                default:
                    statusText = 'Unknown';
            }
            $('#current_status_text').text(statusText);
            
            // Check the appropriate radio button
            $('input[name="new_status"]').prop('checked', false);
            $('input[name="new_status"][value="' + studentStatus + '"]').prop('checked', true);
            
            // Show modal
            $('#statusModal').modal('show');
        });
        
        // Delete button confirmation
        $(document).on('click', '.delete-btn', function(e) {
            if (!confirm(lang.delete_confirm)) {
                e.preventDefault();
                return false;
            }
        });
        
        // Update status button confirmation
        $('#updateStatusBtn').on('click', function(e) {
            var selectedStatus = $('input[name="new_status"]:checked').val();
            if (!selectedStatus) {
                e.preventDefault();
                alert('Please select a status');
                return false;
            }
            if (!confirm(lang.status_update_confirm)) {
                e.preventDefault();
                return false;
            }
        });
        
        // Show/hide filters based on screen size
        function toggleFilters() {
            if ($(window).width() < 768) {
                $('.filter-row .col-md-3').addClass('mb-3');
            } else {
                $('.filter-row .col-md-3').removeClass('mb-3');
            }
        }
        
        // Initial call
        toggleFilters();
        
        // Call on window resize
        $(window).resize(toggleFilters);
    });
    
    // Function to select status by clicking on the option div
    function selectStatus(value) {
        $('input[name="new_status"]').prop('checked', false);
        $('input[name="new_status"][value="' + value + '"]').prop('checked', true);
    }
    </script>

</body>

</html>
<?php
// Close database connection
$conn->close();
?>